/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DynoProductList {
        "name": string;
        "products": any;
        "response": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLDynoProductListElement extends Components.DynoProductList, HTMLStencilElement {
    }
    var HTMLDynoProductListElement: {
        prototype: HTMLDynoProductListElement;
        new (): HTMLDynoProductListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dyno-product-list": HTMLDynoProductListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DynoProductList {
        "name"?: string;
        "products"?: any;
        "response"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "dyno-product-list": DynoProductList;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dyno-product-list": LocalJSX.DynoProductList & JSXBase.HTMLAttributes<HTMLDynoProductListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
