/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DynoProductItem {
        "href": string;
        "label": string;
    }
    interface DynoProductList {
        "name": string;
        "products": any;
    }
}
declare global {
    interface HTMLDynoProductItemElement extends Components.DynoProductItem, HTMLStencilElement {
    }
    var HTMLDynoProductItemElement: {
        prototype: HTMLDynoProductItemElement;
        new (): HTMLDynoProductItemElement;
    };
    interface HTMLDynoProductListElement extends Components.DynoProductList, HTMLStencilElement {
    }
    var HTMLDynoProductListElement: {
        prototype: HTMLDynoProductListElement;
        new (): HTMLDynoProductListElement;
    };
    interface HTMLElementTagNameMap {
        "dyno-product-item": HTMLDynoProductItemElement;
        "dyno-product-list": HTMLDynoProductListElement;
    }
}
declare namespace LocalJSX {
    interface DynoProductItem {
        "href"?: string;
        "label"?: string;
    }
    interface DynoProductList {
        "name"?: string;
        "products"?: any;
    }
    interface IntrinsicElements {
        "dyno-product-item": DynoProductItem;
        "dyno-product-list": DynoProductList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dyno-product-item": LocalJSX.DynoProductItem & JSXBase.HTMLAttributes<HTMLDynoProductItemElement>;
            "dyno-product-list": LocalJSX.DynoProductList & JSXBase.HTMLAttributes<HTMLDynoProductListElement>;
        }
    }
}
